import { HelpRequest } from '../app/models/helper.model';

export const helpers: HelpRequest[] = [
  {
    id: 1,
    requester: 101,
    title: 'Ajuda para tratamento médico',
    update_date_time: new Date(),
    description: 'Apoio financeiro para tratamento médico de emergência.',
    image: '',
    goal: 5000,
    donate_quantity: 10,
    parcial_amount: 2500,
  },
  {
    id: 2,
    requester: 102,
    title: 'Reforma da Escola Comunitária',
    update_date_time: new Date(),
    description: 'Ajuda para reformar a escola da comunidade.',
    image: '',
    goal: 20000,
    donate_quantity: 15,
    parcial_amount: 10000,
  },
  {
    id: 3,
    requester: 103,
    title: 'Ajuda para Alimentação',
    update_date_time: new Date(),
    description: 'Doações para fornecer alimentação a famílias carentes.',
    image: '',
    goal: 3000,
    donate_quantity: 5,
    parcial_amount: 1500,
  },
  {
    id: 4,
    requester: 104,
    title: 'Compra de Material Escolar',
    update_date_time: new Date(),
    description: 'Ajuda para compra de material escolar para crianças.',
    image: '',
    goal: 10000,
    donate_quantity: 20,
    parcial_amount: 4000,
  },
  {
    id: 5,
    requester: 105,
    title: 'Apoio a Abrigo de Animais',
    update_date_time: new Date(),
    description: 'Ajuda financeira para manutenção de abrigo de animais.',
    image: '',
    goal: 7000,
    donate_quantity: 12,
    parcial_amount: 3500,
  },
  {
    id: 6,
    requester: 106,
    title: 'Campanha de Vacinação',
    update_date_time: new Date(),
    description: 'Arrecadação para campanha de vacinação em áreas rurais.',
    image: '',
    goal: 15000,
    donate_quantity: 25,
    parcial_amount: 7500,
  },
  {
    id: 7,
    requester: 107,
    title: 'Construção de Poço Artesiano',
    update_date_time: new Date(),
    description: 'Ajuda para construção de poço artesiano em comunidade rural.',
    image: '',
    goal: 25000,
    donate_quantity: 8,
    parcial_amount: 12500,
  },
  {
    id: 8,
    requester: 108,
    title: 'Suporte a Famílias Desabrigadas',
    update_date_time: new Date(),
    description:
      'Ajuda para suporte a famílias desabrigadas por desastres naturais.',
    image: '',
    goal: 18000,
    donate_quantity: 30,
    parcial_amount: 9000,
  },
  {
    id: 9,
    requester: 109,
    title: 'Compra de Medicamentos',
    update_date_time: new Date(),
    description: 'Ajuda para compra de medicamentos para pessoas carentes.',
    image: '',
    goal: 12000,
    donate_quantity: 18,
    parcial_amount: 6000,
  },
  {
    id: 10,
    requester: 110,
    title: 'Reforma de Centro Comunitário',
    update_date_time: new Date(),
    description: 'Ajuda para reforma do centro comunitário local.',
    image: '',
    goal: 22000,
    donate_quantity: 22,
    parcial_amount: 11000,
  },
  {
    id: 11,
    requester: 111,
    title: 'Ajuda a Lar de Idosos',
    update_date_time: new Date(),
    description: 'Apoio financeiro para manutenção de lar de idosos.',
    image: '',
    goal: 8000,
    donate_quantity: 14,
    parcial_amount: 4000,
  },
  {
    id: 12,
    requester: 112,
    title: 'Apoio a Pequenos Agricultores',
    update_date_time: new Date(),
    description:
      'Ajuda financeira para pequenos agricultores afetados pela seca.',
    image: '',
    goal: 14000,
    donate_quantity: 19,
    parcial_amount: 7000,
  },
  {
    id: 13,
    requester: 113,
    title: 'Educação Infantil',
    update_date_time: new Date(),
    description:
      'Ajuda para projetos de educação infantil em comunidades carentes.',
    image: '',
    goal: 17000,
    donate_quantity: 27,
    parcial_amount: 8500,
  },
  {
    id: 14,
    requester: 114,
    title: 'Projeto de Energia Solar',
    update_date_time: new Date(),
    description:
      'Ajuda para instalação de painéis solares em comunidades rurais.',
    image: '',
    goal: 30000,
    donate_quantity: 10,
    parcial_amount: 15000,
  },
  {
    id: 15,
    requester: 115,
    title: 'Campanha de Alfabetização',
    update_date_time: new Date(),
    description: 'Ajuda para campanha de alfabetização de adultos.',
    image: '',
    goal: 11000,
    donate_quantity: 23,
    parcial_amount: 5500,
  },
  {
    id: 16,
    requester: 116,
    title: 'Apoio Psicológico',
    update_date_time: new Date(),
    description:
      'Ajuda para fornecer suporte psicológico a pessoas em situação de vulnerabilidade.',
    image: '',
    goal: 9000,
    donate_quantity: 16,
    parcial_amount: 4500,
  },
  {
    id: 17,
    requester: 117,
    title: 'Reflorestamento',
    update_date_time: new Date(),
    description: 'Ajuda para projeto de reflorestamento em áreas desmatadas.',
    image: '',
    goal: 25000,
    donate_quantity: 20,
    parcial_amount: 12500,
  },
  {
    id: 18,
    requester: 118,
    title: 'Apoio a Comunidade Indígena',
    update_date_time: new Date(),
    description: 'Ajuda para projetos de apoio a comunidades indígenas.',
    image: '',
    goal: 20000,
    donate_quantity: 15,
    parcial_amount: 10000,
  },
  {
    id: 19,
    requester: 119,
    title: 'Ajuda a Animais de Rua',
    update_date_time: new Date(),
    description: 'Doações para resgate e cuidado de animais de rua.',
    image: '',
    goal: 10000,
    donate_quantity: 18,
    parcial_amount: 5000,
  },
  {
    id: 20,
    requester: 120,
    title: 'Projeto de Inclusão Digital',
    update_date_time: new Date(),
    description:
      'Ajuda para fornecer acesso à internet e computadores a comunidades carentes.',
    image: '',
    goal: 15000,
    donate_quantity: 25,
    parcial_amount: 7500,
  },
  {
    id: 21,
    requester: 121,
    title: 'Suporte a Famílias Refugiadas',
    update_date_time: new Date(),
    description: 'Ajuda financeira para suporte a famílias refugiadas.',
    image: '',
    goal: 18000,
    donate_quantity: 12,
    parcial_amount: 9000,
  },
  {
    id: 22,
    requester: 122,
    title: 'Programa de Saúde Bucal',
    update_date_time: new Date(),
    description: 'Ajuda para programas de saúde bucal em escolas públicas.',
    image: '',
    goal: 7000,
    donate_quantity: 10,
    parcial_amount: 3500,
  },
  {
    id: 23,
    requester: 123,
    title: 'Projeto de Segurança Alimentar',
    update_date_time: new Date(),
    description:
      'Ajuda para projetos de segurança alimentar em comunidades carentes.',
    image: '',
    goal: 13000,
    donate_quantity: 17,
    parcial_amount: 6500,
  },
  {
    id: 24,
    requester: 124,
    title: 'Suporte a Crianças com Câncer',
    update_date_time: new Date(),
    description: 'Ajuda para suporte a crianças em tratamento contra o câncer.',
    image: '',
    goal: 20000,
    donate_quantity: 22,
    parcial_amount: 10000,
  },
];
